services:
  app:
    build: .
    image: jardelberti/agenda.escola:latest
    container_name: agenda_escolar_app
    restart: unless-stopped
    ports:
      - "8080:5000"
    volumes:
      - db_data:/data
volumes:
  db_data:

