"""Adiciona nome_curto ao Usuario

Revision ID: 0af5d1ea5e0c
Revises: 844caed06233
Create Date: 2025-10-07 20:39:56.339283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af5d1ea5e0c'
down_revision = '844caed06233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_curto', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('nome_curto')

    # ### end Alembic commands ###
