"""Adiciona antecedencia minima com server default

Revision ID: 11dd45b6d082
Revises: 980195a7f0be
Create Date: 2025-10-09 21:30:37.128695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dd45b6d082'
down_revision = '980195a7f0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_agendamento_dias', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('min_agendamento_dias')

    # ### end Alembic commands ###
