"""add unique constraint and indexes to booking

Revision ID: 5b7950738002
Revises: b843424c4af1
Create Date: 2026-09-02 16:14:02.004109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7950738002'
down_revision = 'b843424c4af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_unique_constraint('_resource_date_shift_slot_uc', ['resource_id', 'date', 'shift', 'slot_name'])
        batch_op.create_index('idx_booking_resource_date', ['resource_id', 'date'], unique=False)
        batch_op.create_index('idx_booking_teacher_date', ['teacher_id', 'date'], unique=False)

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('resource')]
    if 'is_active' not in columns:
        with op.batch_alter_table('resource', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index('idx_booking_teacher_date')
        batch_op.drop_index('idx_booking_resource_date')
        batch_op.drop_constraint('_resource_date_shift_slot_uc', type_='unique')

    # ### end Alembic commands ###
