"""Adiciona stripe_price_id ao plano

Revision ID: 844caed06233
Revises: e7ffa6180e15
Create Date: 2025-10-05 18:17:42.279455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844caed06233'
down_revision = 'e7ffa6180e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
