"""Adiciona campos de endereço estruturado a escola

Revision ID: 980195a7f0be
Revises: e26100f5d385
Create Date: 2025-10-09 19:30:56.049394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980195a7f0be'
down_revision = 'e26100f5d385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.drop_column('pais')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('numero')
        batch_op.drop_column('endereco')
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
