"""Adiciona campos de info da escola e disciplinas

Revision ID: e26100f5d385
Revises: fce9bdbc4edf
Create Date: 2025-10-09 18:36:38.233798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26100f5d385'
down_revision = 'fce9bdbc4edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_disciplina',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'disciplina_id')
    )
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_diretor', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('email_contato', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('telefone_fixo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telefone_celular', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.drop_column('telefone_celular')
        batch_op.drop_column('telefone_fixo')
        batch_op.drop_column('email_contato')
        batch_op.drop_column('nome_diretor')

    op.drop_table('usuario_disciplina')
    op.drop_table('disciplina')
    # ### end Alembic commands ###
